# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  build_and_test: circleci/build_and_test-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          context: org-global
      - deploy:
          requires:
            - test

